### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by ytaylor** [Adalab/modulo-1-evaluacion-intermedia-Sararid#1]
Muy buen trabajo @Sararid!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

- [x] CARPETAS > IMG: Los ficheros de imágenes deben empezar por `./images/` o `./img/`.
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: Los enlaces tienen que tener el atributo `title`.
- [x] HTML > MAIN: Necesitamos al menos una etiqueta h1 para el contenido de "Creando diversidad digital". No utilices un párrafo para cada palabra, ajusta el texto utilizando propiedades css como el ´width ´ del contenedor. No es necesario utilizar dos elementos contenedores para mostrar la misma información y que se oculte o muestre en dependencia. 
- [x] CSS > FONT-FAMILY: Es recomendable que la fuente del body sea Rubik para aprovechar la herencia.
- [x] CSS > FONT-FAMILY: La fuente del h1 debe ser Rubik
- [x] CSS > FONT-SIZE: El tamaño del h1 en móvil debe ser 30px.
- [x] CSS > FONT-SIZE: El tamaño del h1 en tablet debe ser 40px.
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.
- [x] CSS > CLASES: El fichero CSS no es correcto. Comprueba si has cerrado todas las llaves.
- [ ] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos.

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits también tienen que ser en inglés, empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Con cada mejora que hagas, márcala como completada en este is sue y su súbela a este repo.

> Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by Sararid** [comment]
Muchas gracias por el feedback y la corrección Yannelis! He solucionado todos los puntos menos el último, ya que creo que los elementos ya estaban alineados a la izquierda y derecha, he añadido igual un padding left y right de 30 px en el header (tablet). Si fuera incorrecto, me podrías indicar dónde está el error?

Muchas gracias
Un saludo 
Sara

**Comment by ytaylor** [comment]
Hola Sara, 

Muy bien trabajo, ya está todo correcto. Con respecto a la alineación a la izquierda, efectivamente con el padding cumplimos las reglas especificadas en el diseño: que ponía a cada lado 30px a cada lado del ´header´. 

Si queda cualquier duda, no dudes en preguntarme. 

Saludos,
